import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const {projetoAtivo} = require('./compartilhado/projeto.cjs');

type Secao = {id: string; rotulo: string};

/**
 * Uma sidebar autogerada por seção declarada no projeto.json.
 *
 * Os ids seguem o padrão `<secao>Sidebar` e são os mesmos referenciados pela
 * navbar em docusaurus.config.ts — mudar aqui exige mudar lá.
 */
const projeto = projetoAtivo();

const sidebars: SidebarsConfig = Object.fromEntries(
  (projeto.secoes as Secao[]).map((secao) => [
    `${secao.id}Sidebar`,
    [{type: 'autogenerated', dirName: secao.id}],
  ]),
);

export default sidebars;
